version: '3.8'

services:
  usuario:
    build:
      context: ./usuario-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://root:password@mongo:27017/mi_proyecto?authSource=admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  cuenta:
    build:
      context: ./cuenta-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mongo
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://root:password@mongo:27017/mi_proyecto?authSource=admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mi_proyecto
    volumes:
      - mongodata:/data/db

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

volumes:
  mongodata: